#!/usr/bin/env python3
# ═══════════════════════════════════════════════════════════════
# DCS COMPONENTS.md generator
# Scans js/dcs-*.js, extracts registration name, data-action verbs,
# custom data-* attributes, matching CSS, ARIA + keyboard features,
# and emits a Markdown reference at COMPONENTS.md.
# ═══════════════════════════════════════════════════════════════
import os
import re
import glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JS_DIR = os.path.join(ROOT, 'js')
CSS_DIR = os.path.join(ROOT, 'css')
OUT = os.path.join(ROOT, 'COMPONENTS.md')

# Files that are build artifacts / bundles / superseded, not source components.
SKIP = {'dcs-components.min.js', 'guide.min.js'}
# Skip legacy/superseded variants (e.g. dcs-checkboxes-v1.js).
SKIP_SUFFIXES = ('-v1.js',)

REGISTER_RE = re.compile(r"""DCS\.register\(\s*['"]([^'"]+)['"]""")
ACTION_RE = re.compile(r"""data-action=["']([^"']+)["']""")
# Custom data-* attributes referenced via getAttribute / setAttribute / selectors.
DATA_ATTR_RE = re.compile(r"""['"\[](data-[a-z0-9-]+)['"\]=]""")
ROLE_RE = re.compile(r"""setAttribute\(\s*['"]role['"]\s*,\s*['"]([^'"]+)['"]""")
ARIA_RE = re.compile(r"""(aria-[a-z]+)""")
KEY_RE = re.compile(r"""e\.key\s*===?\s*['"]([^'"]+)['"]""")

# data-* attributes that are infrastructure, not per-component config.
INFRA_DATA = {'data-action', 'data-dcs-component', 'data-dcs-initialized',
              'data-dcs-instance', 'data-theme'}


def humanize(name):
    return name.replace('-', ' ').replace('_', ' ').title()


def scan_file(path):
    src = open(path, encoding='utf-8').read()
    names = REGISTER_RE.findall(src)
    if not names:
        return None
    actions = sorted(set(ACTION_RE.findall(src)))
    data_attrs = sorted(set(
        a for a in DATA_ATTR_RE.findall(src) if a not in INFRA_DATA
    ))
    roles = sorted(set(ROLE_RE.findall(src)))
    arias = sorted(set(ARIA_RE.findall(src)))
    keys = sorted(set(KEY_RE.findall(src)))
    return {
        'file': os.path.basename(path),
        'names': names,
        'actions': actions,
        'data_attrs': data_attrs,
        'roles': roles,
        'arias': arias,
        'keys': keys,
    }


def css_for(name):
    """Return the matching css filename if one exists, else None."""
    # Try direct match then a couple of common pluralization variants.
    candidates = [name, name + 's', name.rstrip('s')]
    # A few known aliases where JS name != CSS file stem.
    aliases = {
        'modal': 'modals', 'toggle': 'toggles', 'toast': 'toasts',
        'checkbox': 'checkboxes', 'chip': 'chips', 'badge': 'badges',
        'input': 'inputs', 'button': 'buttons', 'card': 'cards',
        'table': 'tables', 'pagination': 'pagination', 'code': 'code-blocks',
        'combobox': 'combo-box', 'palette': 'command-palette',
        'dropzone': 'file-drop-zone', 'image-compare': 'image-comparison',
        'header': 'header-nav', 'empty': 'empty-state', 'kpi': 'kpi-cards',
        'sticky-bar': 'sticky-action-bar', 'alert': 'alert-banner',
        'search': 'search-input', 'dropdown': 'dropdown-select',
        'scrollspy': 'scroll-spy', 'theme': 'dcs-core',
    }
    if name in aliases:
        candidates.insert(0, aliases[name])
    for c in candidates:
        p = os.path.join(CSS_DIR, c + '.css')
        if os.path.isfile(p):
            return c + '.css'
    return None


def collect():
    comps = []
    infra = []  # dcs-*.js files with no registered component (helpers/glue)
    for path in sorted(glob.glob(os.path.join(JS_DIR, 'dcs-*.js'))):
        base = os.path.basename(path)
        if base in SKIP or base.endswith(SKIP_SUFFIXES):
            continue
        info = scan_file(path)
        if info:
            comps.append(info)
        else:
            infra.append(base)
    return comps, infra


def render(comps, infra):
    L = []
    L.append('# DCS Component Reference')
    L.append('')
    L.append('> Auto-generated by `tools/gen-components-doc.py` — do not edit by hand.')
    L.append('> Regenerate with `python3 tools/gen-components-doc.py`.')
    L.append('')
    total = sum(len(c['names']) for c in comps)
    L.append(f'**{total} components** registered across **{len(comps)}** source files.')
    L.append('')

    # ── Quick-reference table ──
    L.append('## Quick Reference')
    L.append('')
    L.append('| Component | Source | CSS | Actions | ARIA roles | Keyboard |')
    L.append('|-----------|--------|-----|---------|-----------|----------|')
    for c in comps:
        for name in c['names']:
            css = css_for(name)
            actions = ', '.join('`{}`'.format(a) for a in c['actions']) if c['actions'] else '—'
            L.append('| `{}` | `js/{}` | {} | {} | {} | {} |'.format(
                name,
                c['file'],
                '`css/{}`'.format(css) if css else '—',
                actions,
                ', '.join(c['roles']) if c['roles'] else '—',
                '✓' if c['keys'] else '—',
            ))
    L.append('')
    if infra:
        L.append('**Infrastructure-only** (`dcs-*.js` with no registered component): ' +
                 ', '.join('`{}`'.format(f) for f in infra) + '.')
        L.append('')

    # ── Usage pattern ──
    L.append('## Usage Pattern — the DCS init lifecycle')
    L.append('')
    L.append('DCS has no build-time framework. Every component is a plain-JS controller')
    L.append('registered against a central registry in `js/dcs-core.js`.')
    L.append('')
    L.append('1. **Register** — each `js/dcs-*.js` file calls')
    L.append('   `window.DCS.register(\'name\', { init: function(el) { ... } })`.')
    L.append('2. **Mark up** — author HTML with `data-dcs-component="name"` on the root')
    L.append('   element of an instance.')
    L.append('3. **Init** — `DCS._init(container)` scans for')
    L.append('   `[data-dcs-component]:not([data-dcs-initialized])`, stamps each with')
    L.append('   `data-dcs-instance` + `data-dcs-initialized`, and invokes the')
    L.append('   controller\'s `init(el)`. It is idempotent — already-initialized nodes')
    L.append('   are skipped, so it is safe to call repeatedly (e.g. after injecting')
    L.append('   markup dynamically).')
    L.append('4. **Auto-init** — core fires `initAll()` on `DOMContentLoaded`, again on')
    L.append('   `window.load`, and once more after a 500 ms timeout to catch components')
    L.append('   registered late.')
    L.append('')
    L.append('```html')
    L.append('<!-- Load order: core first, then any component scripts -->')
    L.append('<script src="js/dcs-core.js"></script>')
    L.append('<script src="js/dcs-modal.js"></script>')
    L.append('')
    L.append('<div data-dcs-component="modal"> ... </div>')
    L.append('```')
    L.append('')
    L.append('Shared helpers exposed on `window.DCS`:')
    L.append('')
    L.append('- `DCS._trapFocus(container)` → traps Tab/Shift+Tab focus, returns a')
    L.append('  `release()` that restores focus to the trigger. Used by modal, drawer,')
    L.append('  bottom sheet, command palette.')
    L.append('- `DCS._focusable(container)` → visible focusable descendants in DOM order.')
    L.append('- `DCS._showToast(message, type)` → transient live-region toast')
    L.append('  (`type`: `info` \\| `success` \\| `warning` \\| `error` \\| `danger`).')
    L.append('')

    # ── Per-component detail ──
    L.append('## Components')
    L.append('')
    for c in comps:
        for name in c['names']:
            css = css_for(name)
            L.append(f'### `{name}`')
            L.append('')
            L.append(f'- **Source:** `js/{c["file"]}`')
            L.append(f'- **Stylesheet:** {"`css/" + css + "`" if css else "_(none found)_"}')
            L.append('')
            L.append('**HTML usage**')
            L.append('')
            L.append('```html')
            L.append(f'<div data-dcs-component="{name}">')
            if c['actions']:
                L.append(f'  <button data-action="{c["actions"][0]}">…</button>')
            L.append('  <!-- component markup -->')
            L.append('</div>')
            L.append('```')
            L.append('')
            if c['actions']:
                L.append('**Actions** (`data-action="…"`)')
                L.append('')
                for a in c['actions']:
                    L.append(f'- `{a}`')
                L.append('')
            if c['data_attrs']:
                L.append('**Data attributes**')
                L.append('')
                for d in c['data_attrs']:
                    L.append(f'- `{d}`')
                L.append('')
            # Accessibility notes
            notes = []
            if c['roles']:
                notes.append('- ARIA roles: ' + ', '.join('`{}`'.format(r) for r in c['roles']))
            aria_states = [a for a in c['arias'] if a != 'aria-']
            if aria_states:
                notes.append('- ARIA attributes: ' + ', '.join('`{}`'.format(a) for a in aria_states))
            if c['keys']:
                notes.append('- Keyboard: ' + ', '.join('`{}`'.format(k) for k in c['keys']))
            if notes:
                L.append('**Accessibility**')
                L.append('')
                L.extend(notes)
                L.append('')
            L.append('---')
            L.append('')

    return '\n'.join(L) + '\n'


def main():
    comps, infra = collect()
    md = render(comps, infra)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(md)
    total = sum(len(c['names']) for c in comps)
    print(f'Wrote {OUT}: {total} components from {len(comps)} files '
          f'({len(infra)} infrastructure-only).')


if __name__ == '__main__':
    main()
